# Generated by Django 5.0.1 on 2024-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('user_type', models.TextField(choices=[('seeker', 'seeker'), ('company', 'company')])),
                ('pwd', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
