# Generated by Django 4.2.4 on 2024-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('file', models.ImageField(default='', upload_to='profile/')),
            ],
        ),
    ]
